spring:
 jta:
  atomikos:
   properties:
    max-timeout: 900000

datasource:
 db1:
  unique-resource-name: oracle-db1
  xa-data-source-class-name: oracle.jdbc.xa.client.OracleXADataSource
  xa-properties:
   user: hr
   password: hrpw
   URL: jdbc:oracle:thin:@//localhost:1531/orclpdb1.localdomain
  min-pool-size: 1
  max-pool-size: 2
 db2:
  unique-resource-name: oracle-db2
  xa-data-source-class-name: oracle.jdbc.xa.client.OracleXADataSource
  xa-properties:
   user: hr
   password: hrpw
   URL: jdbc:oracle:thin:@//localhost:1532/orclpdb1.localdomain
  min-pool-size: 1
  max-pool-size: 2